### ISSUE TITLE
Update: Readme

### ISSUE THREAD

**Issue by rohitt-gupta** [rohitt-gupta/dominate-links#12]
PS- Try to not use AI for content as it is clearly differentiating to the reader
### Add HLD to readme
- Add a high-level HLD plan with Flowcharts for the project readme.
- The HLD and LLD diagrams should be explained in such a way that any person can understand how the application is working
- Add 2 flow charts.
1. Explaining the user actions flow.
2. Explained the module-level flow 
- Add a small piece of content to explain the flow charts.

### Add Contact information 
- Add content information as a link for this discord server and Twitter link @whyrohitwhy or any squad member

### Improve Docs
- make pnpm mandatory
- Use/Improve the appropriate size of font such as
  Heading is big
  Subheading is small
  paragraph is smallest
- Make the readme attractive and warm, genuine(not AI-generated)
- Refer other open source repositories if possible

**Comment by Param302** [comment]
Hi @rohitt-gupta ,

I would like to work on this issue!
